blank_issues_enabled: false
contact_links:
  - name: Discussions, questions, and non-project issues
    url: https://jq.qq.com/?_wv=1027&k=I1oJKSTH
    about: For anything that is not an explicit bug
